# Generated by Django 6.0.5 on 2026-05-27 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='assigned_engineer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_approved': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='portal.engineerprofile'),
        ),
    ]
