# Generated by Django 6.0.5 on 2026-05-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_helprequest_assigned_engineer'),
    ]

    operations = [
        migrations.AddField(
            model_name='vindecoderecord',
            name='api_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vindecoderecord',
            name='api_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vindecoderecord',
            name='body_class',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='vindecoderecord',
            name='decoded_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vindecoderecord',
            name='engine',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='vindecoderecord',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='vindecoderecord',
            name='make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vindecoderecord',
            name='model',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='vindecoderecord',
            name='part_number_query',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='vindecoderecord',
            name='plant',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='vindecoderecord',
            name='source',
            field=models.CharField(default='NHTSA vPIC', max_length=80),
        ),
        migrations.AddField(
            model_name='vindecoderecord',
            name='transmission',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='vindecoderecord',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
