# Generated by Django 6.0.5 on 2026-05-27 15:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_vindecoderecord_api_available_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticFileAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('cbf', 'CBF'), ('smr-d', 'SMR-D'), ('cff', 'CFF')], max_length=10)),
                ('uploaded_file', models.FileField(upload_to='diagnostic_file_library/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['cbf', 'smr-d', 'smrd', 'cff'])])),
                ('original_file_name', models.CharField(blank=True, max_length=255)),
                ('ecu_name', models.CharField(max_length=120)),
                ('ecu_part_number', models.CharField(blank=True, max_length=120)),
                ('hardware_number', models.CharField(blank=True, max_length=120)),
                ('software_number', models.CharField(blank=True, max_length=120)),
                ('compatible_brand', models.CharField(default='Mercedes-Benz', max_length=80)),
                ('compatible_models', models.CharField(help_text='Models or platforms confirmed for this file, e.g. W204 C-Class, W212 E-Class.', max_length=255)),
                ('year_range', models.CharField(blank=True, help_text='Optional confirmed years, e.g. 2012-2015.', max_length=80)),
                ('engine_or_variant', models.CharField(blank=True, max_length=150)),
                ('diagnostic_tool', models.CharField(blank=True, help_text='e.g. Vediamo or DTS Monaco.', max_length=100)),
                ('compatibility_notes', models.TextField(blank=True)),
                ('extracted_text_preview', models.TextField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diagnostic file asset',
                'ordering': ['-created_at'],
            },
        ),
    ]
