# Generated by Django 6.0.5 on 2026-05-27 15:10

import django.db.models.deletion
import portal.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_diagnosticfileasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredVehiclePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=150)),
                ('part_number', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('engine', 'Engine'), ('brake', 'Brake'), ('electrical', 'Electrical / ECU'), ('service', 'Service / Maintenance'), ('suspension', 'Suspension'), ('transmission', 'Transmission'), ('other', 'Other')], default='other', max_length=30)),
                ('is_required', models.BooleanField(default=True)),
                ('exact_vin', models.CharField(blank=True, help_text='Optional: restrict this part to one specific vehicle VIN.', max_length=17, validators=[portal.utils.validate_vin])),
                ('compatible_make', models.CharField(default='MERCEDES-BENZ', max_length=100)),
                ('compatible_model', models.CharField(max_length=120)),
                ('year_from', models.PositiveIntegerField(blank=True, null=True)),
                ('year_to', models.PositiveIntegerField(blank=True, null=True)),
                ('engine_or_variant', models.CharField(blank=True, max_length=150)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Required vehicle part',
                'ordering': ['category', 'part_name'],
            },
        ),
    ]
