# Generated by Django 6.0.5 on 2026-05-27 15:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_requiredvehiclepart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='engineerprofile',
            name='id_type',
            field=models.CharField(choices=[('nin', 'National Identification Number (NIN)'), ('drivers_licence', "Driver's Licence"), ('passport', 'International Passport'), ('voters_card', "Voter's Card"), ('other', 'Other Government ID')], default='nin', max_length=30),
        ),
        migrations.AddField(
            model_name='engineerprofile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engineerprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineer_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engineerprofile',
            name='verification_document',
            field=models.FileField(blank=True, upload_to='engineer_verification/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AddField(
            model_name='engineerprofile',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='engineerprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='assigned_engineer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_approved': True, 'verification_status': 'approved'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='portal.engineerprofile'),
        ),
    ]
